### ISSUE TITLE
Issue resolving _ package versions

### ISSUE THREAD

**Issue by adgang** [deno-plc/vite-plugin-deno#2]
```
[h3] [unhandled] Error: Expectation failed: underscore version extension differs while processing package '@tanstack/react-router'@'1.81.10' processing '@tanstack/react-router@1.81.10_react@18.3.1_react-dom@18.3.1__react@18.3.1' hit '@tanstack/react-router@1.81.10_@tanstack+router-generator@1.81.9_react@18.3.1_react-dom@18.3.1__react@18.3.1'. Please file an issue: https://github.com/deno-plc/vite-plugin-deno/issues/new

...
Caused by Error: Expectation failed: underscore version extension differs while processing package '@tanstack/react-router'@'1.81.10' processing '@tanstack/react-router@1.81.10_react@18.3.1_react-dom@18.3.1__react@18.3.1' hit '@tanstack/react-router@1.81.10_@tanstack+router-generator@1.81.9_react@18.3.1_react-dom@18.3.1__react@18.3.1'. Please file an issue: https://github.com/deno-plc/vite-plugin-deno/issues/new
    at ModuleGraph.get_deno_info (https://jsr.io/@deno-plc/vite-plugin-deno/2.1.9/src/graph.ts:288:31)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async ModuleGraph.update_info (https://jsr.io/@deno-plc/vite-plugin-deno/2.1.9/src/graph.ts:346:9)
    at async ModuleGraph.get_module (https://jsr.io/@deno-plc/vite-plugin-deno/2.1.9/src/graph.ts:426:13)
    at async resolve (https://jsr.io/@deno-plc/vite-plugin-deno/2.1.9/src/resolve.ts:97:25)
    at async ResolveIdContext.handler (https://jsr.io/@deno-plc/vite-plugin-deno/2.1.9/mod.ts:153:34)
    ```

**Comment by hansSchall** [comment]
First of all (but completely unrelated to the error): It looks like you are using React, but as stated in the Readme this is currently unsupported :-( I have never used tanstack and therefore never tested its compatibility with this plugin. It looks like it is using a pretty complex build process which might break things. In general full-stack frameworks do not support swapping out things...

Additionally I am unable to reproduce the error, but maybe it is mac-only or caused by your environment (I was testing in Github Codespaces). When I tried it, it failed with another error about non-existent files...

With the error you hit a quite rare case: Deno reports the same npm dependency twice. The used JSON format allows this, but I could not find any documentation on this behavior and was not able to test such a case. In order to fully understand the situation it would help a lot if you could pipe the output of `deno info --json <your entrypoint>` to a file and share it alongside with your `deno.lock`.

**Comment by adgang** [comment]
:D Thank you very much for the quick response. Is there any alternative to get react working on deno with vite? 
Tanstack is based on vinxi which is based on nitro. These seem to be pretty standard in toolchain these days(There are going to be a dozen more frameworks using vinxi soon).

On reproduction(in case you still want to check):
May be with this change in @tanstack/start (inside node_modules), you should be able to reproduce the issue.
https://github.com/adgang/router/commit/eb47080aa8cab4146dd7bebcc7b5b24d4c4dbc71
Since the npm package will have dist folder, you also need to add to line 193 of `@tanstack/start/dist/esm/config`(adding a new key to the return value of `function setTsrDefaults(config) {`).

```
addExtensions: navigator.userAgent.startsWith('Deno'),
```

I will get the `deno info` and paste it here.
